name: GPU-EpetraOFF

# Trigger the workflow on merge to NGA-FY23-develop
on:
  pull_request:
    branches:
      - NGA-FY23-develop

  workflow_dispatch:

jobs:
  check_requirements:  
    runs-on: nvidia/cuda:12.2.0-devel-ubuntu22.04
    steps:
    - name: Check Cuda Requirements
      run: |
        apt-get update && apt-get install -y git \
        cd /opt
        git clone https://github.com/NVIDIA/cuda-samples.git
        cd /opt/cuda-samples/Samples/1_Utilities/deviceQuery
        make dbg=1 TARGET_ARCH=x86_64 HOST_COMPILER=g++

  build:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: CI Variables
        id: vars
        run: echo "DOCKER_TAG=$(echo ${{ github.ref }} | cut -d'/' -f3- | sed 's/[^a-z0-9_-]/__/gi')" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - name: Inspect Builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
          echo "DOCKER_TAG: ${{ env.DOCKER_TAG }}"
          echo "SCOPE_NAME  ${{ env.SCOPE_NAME }}"
      - name: Build and test the Docker Image
        id: docker_build
        continue-on-error: false
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ env.DOCKER_TAG }}
          context: .
          file: ./nga-ci/gpu-epetraOFF.dockerfile
