name: MPI-EpetraON

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - NGA-FY23-develop
  workflow_dispatch:

# Cancel any existing jobs
concurrency:
  group: ${{ github.event.repository.name }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: CI Variables
        id: vars
        run: echo "DOCKER_TAG=$(echo ${{ github.ref }} | cut -d'/' -f3- | sed 's/[^a-z0-9_-]/__/gi')" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Inspect Builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
          echo "DOCKER_TAG: ${{ env.DOCKER_TAG }}"
          echo "SCOPE_NAME  ${{ env.SCOPE_NAME }}"
      - name: Build and test the Docker Image
        id: docker_build
        continue-on-error: false
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ env.DOCKER_TAG }}
          context: .
          file: ./nga-ci/mpi-epetraON.dockerfile
